name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 停止并删除现有容器
            docker stop frontend || true
            docker rm frontend || true

            # 尝试删除旧镜像
            docker rmi sustechcs304/frontend:latest || true

            # 拉取最新镜像
            docker pull sustechcs304/frontend:latest

            # 启动新容器，将宿主机的 45632 端口映射到容器的 80 端口
            docker run -d --name frontend -p 45632:80 sustechcs304/frontend:latest
